ferdium/ferdium-recipes

scripts/package.js
According to usage documentation of jsDelivr all GH repositories are mirrored:
https://github.com/jsdelivr/jsdelivr#usage-documentation
That means our recipes are available here:
https://cdn.jsdelivr.net/gh/ferdium/ferdium-recipes/recipes/
Should solve #7
=> New jsdelivr URL for Ferdium

recipes/telegram/package.json, recipes/telegram/webview.js
This PR fixes the detection of Telegram WebZ version by assuming it's the Z version if it's not K.
Fixes #12
=> Fix: Telegram WebZ detection

recipes/discord/package.json, recipes/discord/webview.js, recipes/skype/package.json, recipes/skype/webview.js, recipes/steamchat/package.json, recipes/steamchat/webview.js, recipes/zoom/package.json, recipes/zoom/webview.js
This option can be used to allow the user to choose how to handle links
(whether to open in the default browser or within the service itself)
This is a companion PR to the similar [PR in the main repo](https://github.com/ferdium/ferdium-app/pull/154). Need to approve and merge them together
=> Add new service-level option 'trapLinkUrls'

recipes/gmail/package.json, recipes/gmail/webview.js
in gmail there are settings for different styles of inboxes. if this is set to "priority inbox" or "important first", the unread count consists of two numbers:
The first number is the number of unread "important" messages and the second number is the number of all unread messages.
Before Ferdium would read a wrong count and report this situation as 12 unread messages which is clearly wrong. I decided to change that so that the first number is reflected in the unread message count and the second number is used for the "indirect message" count
=> [Gmail] add support for priority inbox

recipes/whatsapp/package.json, recipes/whatsapp/service.css
This PR fixes https://github.com/ferdium/ferdium-recipes/issues/45 and removes Whatsapp max width limited of 1600px.
=> Remove whatsapp max width limit of 1600px

recipes/instagram/package.json, recipes/instagram/webview.js
This fixes https://github.com/ferdium/ferdium-recipes/issues/43 by adding the native handling of dark mode theme for Instagram. This disables the Ferdium injection of CSS for Instagram.
=> Add the native dark mode theme for Instagram

recipes/element/package.json, recipes/element/webview.js
Current method isn't working in all cases, e.g. when avatars line (or IMO recent active chats line) is disabled.
This PR goes to badges parsing in rooms list. Potentially it might be slow if joined rooms count is big, but most reliable, because recent active chats line or Spaces elements for rooms, favorites and privates in sidebar can be disabled.
=> Switch from counting of space-badges to room tile badges for Element

recipes/whatsapp/package.json, recipes/whatsapp/webview-unsafe.js, recipes/whatsapp/webview.js
This is a workaround for Whatsapp Web UI constant lagging due to Whatsapp abusing history.pushState().
This MAY introduce other problems, but we have few conclusive reports on that so far.
=> Workaround for Whatsapp Web UI lag

.github/PULL_REQUEST_TEMPLATE/add_recipe.md
As in https://github.com/ferdium/ferdium-recipes/pull/98#issuecomment-1173237784 mentioned, yarn is no longer used - therefore here the updated PR template.
=> yarn is no longer used - use pnpm instead

recipes/discord/package.json, recipes/discord/webview.js
Since we implemented `trapLinkClicks` we broke some of discord functionalities (such as processing its internal links correctly - which now open in the browser instead).
This fixes that issue.
=> Fix in app URLs for discord

recipes/github/webview.js
GitHub badge count detection was simplified to:
- avoid `if`s;
- improve selector for indirect count element so additional JavaScript content checking would not be necessary.
=> Simplify GitHub badge count detection

recipes/office365-owa/package.json, recipes/office365-owa/webview.js
The error handling pretty much, wont try to `.textContent` if there is no `document.querySelectorAll("span[title*='Inbox'] + div > span")[0]`
It was throwing errors on the landing page because `/\/owa/` is true on that page
=> Error Handling on Office 365 landing page

recipes/messenger/package.json, recipes/messenger/webview.js
Messenger notification badges weren't showing given the previous bad implementation of `Ferdium.loop` and `hideInstallMessage` (I'm to blame about this 😢)
=> fix: messenger badge counter and hideInstallMessage

.github/workflows/builds.yml, .husky/pre-commit, package.json, recipes/messenger/webview.js
This PR adds a step in the CI build on PRs to check that `eslint` reports no errors, as requested in https://github.com/ferdium/ferdium-recipes/pull/95#issuecomment-1173158170.
The names of the `package.json`'s scripts have also been modified to match thoses in [ferdium-app's `package.json`](https://github.com/ferdium/ferdium-app/blob/develop/package.json).
This GitHub repository should enforce a passing CI to merge PRs.
=> ci: add lint and prettier to the pr checks

recipes/whatsapp/package.json, recipes/whatsapp/service.css, recipes/whatsapp/webview.js
This PR fixes an issue with Whatsapp Native Theming when users try to change it using the Whatsapp UI (and not through Ferdium). This issue is described in https://github.com/ferdium/ferdium-app/issues/490 and https://github.com/ferdium/ferdium-app/issues/535.
Now, users will have a popup window like shown in the image whenever they try to change the theme through the whatsapp UI.
=> fix: add warning to whatsapp theming

recipes/cinny/icon.svg, recipes/cinny/index.js, recipes/cinny/package.json, recipes/cinny/webview.js
Service: [Cinny](https://cinny.in/)
URL: https://app.cinny.in/
Service ID: `cinny`
```bash
> ferdium-recipes@1.0.1 package /home/orax/tmp/ferdium-recipes
> node scripts/package.js
✅ Successfully packaged and added 250 recipes (0 unsuccessful recipes)
```
Cinny is a Matrix client, an alternative to [Element](https://element.io/), which has been published alongside it on the official [matrix.org clients page](https://matrix.org/clients/). I feel like including alternative clients for the Matrix ecosystem in Ferdium can only be a good thing !
=> Add Cinny recipe

recipes/element/package.json, recipes/element/webview.js
Element recipe was updated to get direct messages count from the spaces navigation bar as previously it was retrieved only from the active space resulting in situations when there are new messages in Element but there is no indicator if the currently selected Element space does not have unread notifications.
I am not completely sure if these changes do not break something, but from my side everything seemed fine.
Additionally, I could not find any setting in Element that would disable spaces, so I am considering these changes quite safe.
=> Get Element messages count from the spaces navbar

recipes/standardnotes/package.json
changes the serviceUrl as per the screenshot from #265
=> fix #265: change to the service url for standardnotes

recipes/element/package.json, recipes/element/webview.js
This change uses unread rooms instead of messages count like Element (web)app does
Unread rooms count is extracted from the `title` tag.
This is one of the two suggested solutions for #268.
Personally I prefer this over #271.
Before:
After:
If this pull request is accepted, #271 should be closed.
=> Use unread rooms count like Element app does

recipes/mastodon/package.json
Fixes mastodon recipe which add teamId assigned incorrectly. It should use the hosted option instead (as per discussed with @vraravam [here](https://discord.com/channels/963836780778512454/963841911376982046/1065200823803584564))
| Before | After |
|-- |-- |
| ![image](https://user-images.githubusercontent.com/37463445/213205441-d83a534b-703e-4b00-96ba-1370fd7bc467.png) | ![image](https://user-images.githubusercontent.com/37463445/213205492-4ad6c99a-0068-4329-a707-d1e1164a69bb.png)
=> fix: add mastodon hosted option and remove teamId

recipes/yahoo-mail/package.json, recipes/yahoo-mail/webview.js
`data-test-unread-count` attribute does not exist anymore. Using text content of notification `span` element.
=> Fix unread notifications count for yahoo-mail

recipes/pixelfed/package.json
I added the option to enter a custom URL on the Pixelfed service, in order to make it possible to use an hosted instance.
Closes https://github.com/ferdium/ferdium-app/issues/963
=> Add custom URL option on Pixelfed

recipes/amazon-work-mail/package.json
I fixed the URL of the Amazon WorkMail service. The variable name in the URL should be `teamId` and not `teamID`. Fixes https://github.com/ferdium/ferdium-app/issues/1134.
=> Fix URL in Amazon WorkMail

recipes/googleclassroom/package.json, recipes/googleclassroom/webview.js
I implemented the same fix as on Google Calendar, that of https://github.com/ferdium/ferdium-recipes/commit/be1bdd785b7ba739ea6c51c2d960499b04052501, in Google Classroom, to redirect the user on the log-in page if not already logged in. See https://github.com/ferdium/ferdium-app/issues/1064.
=> Fix Google Classroom landing page

package.json
Changed the `pnpm lint` and `pnpm lint:fix` subcommands to use `pnpm dlx` instead of `pnpx` as the later is deprecated.
This is a problem for new contributors who try to follow the instructions to run `pnpm lint:fix` before opening a PR, only to find it doesn't work with their version of `pnpm`.
=> Do not use pnpx in lint and lint:fix

recipes/github/package.json, recipes/github/webview.js
GitHub's notification page no longer updates the notification count when notifications arrive. Instead, it displays a small message saying "COUNT new notifications".
This PR includes that COUNT in the number of direct messages reported to Ferdium.
For example, with this update, my GitHub icon in Ferdium shows 7 direct messages, 4 of which come from the inbox, and 3 of which come from the "new notifications" banner. Prior to this commit, the GitHub icon would only show the 4 direct messages from the inbox.
=> fix(github): Include "new notifications" in direct total

recipes/tt-rss/README.md, recipes/tt-rss/package.json, recipes/tt-rss/webview.js
As described in the updated README for tt-rss, users can now choose to limit notifications to only new articles published under a Category of their choosing. Articles published in other Categories are then considered "indirect" messages.
This feature is made available via parsing a custom URL parameter from the Service URL. Preferrably Ferdium would enable recipies to request custom fields from users, but for now this workaround accomplishes the task.
=> feat(tt-rss): Optionally limit notifications to a Category.

recipes/telegram/package.json, recipes/telegram/webview.js
I modified Telegram’s recipe so that links which contain `t.me` or `web.telegram.org` open within Ferdium no matter what the setting for all links is and despite their `target="_blank"`.
Fixes https://github.com/ferdium/ferdium-app/issues/1275
=> Open Telegram links within Ferdium

recipes/instagram-direct-messages/package.json, recipes/instagram-direct-messages/webview.js, recipes/instagram/package.json, recipes/instagram/webview.js
The messages count on Instagram wasn’t updated after having read the last unread message because `element.textContent` was `''` instead of `0`. So I updated the code to set the count to 0 if `element.textContent` is an empty string.
=> Fix Instagram messages count

.github/workflows/builds.yml, .github/workflows/check-pr.yml, package.json
- use `ubuntu-22.04` runner instead of `ubuntu-20.04`
- use `pnpm/action-setup` instead of handling `pnpm install` manually
- upgrade `tj-actions/changed-files` from v36 to v37
- define `packageManager` config option in `package.json` which is read by `pnpm/action-setup`
=> ci: modernize github actions

recipes/google-calendar/package.json, recipes/google-calendar/webview.js
Based on https://github.com/ferdium/ferdium-app/issues/1086\#issuecomment-1656926137, fixed google calendar recipe to load the external css.
=> Update google-calendar recipe to load external scripts to fix CSP error

recipes/hangoutschat/package.json, recipes/hangoutschat/webview.js
Add reference to workspace.google.com to redirect to login page, similar to other google services like Calendar and Mail
=> Allow gchat login page

recipes/telegram/package.json, recipes/telegram/webview.js
This is the weirdest fix I've ever done, but it seems like if we "override" somehow the `window.onload()` we fix the issue described on https://github.com/ferdium/ferdium-app/issues/1275 (came upon this while trying to solve the issue). Basically, the problem is that whenever we click a button we push a new route that has a script to check for the window.protoUrl and then if it starts with `t.me` tries to navigate to the `tg://` deeplink. Seems like by introducing the `window.onload` method we somehow fix the behaviour, preventing it from navigating to deeplink.
Would be good if someone also tested this PR before merging as this fix is kind of weird.
=> Fix telegram deeplink by adding empty onload

recipes/whatsapp/package.json, recipes/whatsapp/webview.js
…ions.
This is a bugfix for [issue #1303](https://github.com/ferdium/ferdium-app/issues/1303). Unread counts/badges were erroneously incrementing for Whatsapp conversations that were marked as muted. When mute option "Always" is chosen in Whatsapp Web, the value of `chat.muteExpiration` in webview.js is set to `-1`, however the conditional that governs incrementing of unread counts expected a positive non-zero value in this variable to indicate a muted conversation. Chaging the comparison from `> 0` to `!= 0` solved the issue.
=> Fix Whatsapp recipe unread counts for muted conversations

recipes/todoist/package.json, recipes/todoist/webview.js
Why:
* no counters shown for todoist integration; caused
by todoist moving to use generated class names.
This change addreses the need by:
* use absolute element selectors instead of class names
not as nice, but works as of now.
=> fix counters in todoist

recipes/skype/package.json, recipes/skype/webview.js
Added code so that file downloads in Skype will always open in Ferdium rather than an external browser. File downloads are handled by Skype as URLs, but they're different from links to external websites, as rather than opening a page it's just a redirect for a download from the Skype servers. Opening file downloads in Ferdium should be the expected behavior. (The file download might not even work if opened in an external browser.)
This now means users can have “Open URLs in Ferdium” disabled, so that they can visit external links in their main browser, while still having the proper file download behavior.
=> Update Skype's webview.js for file downloads

recipes/asana/package.json, recipes/asana/webview.js
The class name for the notification indicator in Asana has changed recently to `SidebarTopNavLinks-notificationsButtonIndicator`.
This commit updates the Asana recipe to look for this element so the badge indicate will be properly set.
=> Fix badge indicator for Asana recipe

featured.json
- change `googlecalendar` to `google-calendar` in `featured.json`
=> fix: featured json pointing to wrong google calendar recipe id

recipes/slack/package.json, recipes/slack/webview.js
- update selector for team menu to work with new and old slack ui
- bump slack recipe to v1.6.0
References https://github.com/ferdium/ferdium-app/issues/1371
Slack service has the icon again:
=> feat: support for the new slack ui

recipes/thelounge/package.json, recipes/thelounge/webview.js
Fixed an issue in TheLounge where it would produce notifications for muted channels and servers.
=> Fix TheLounge sending notifications for muted channels

recipes/instagram/package.json, recipes/instagram/webview.js
- [x ] I have read the [Contributing Guidelines](https://github.com/ferdium/ferdium-recipes/blob/HEAD/CONTRIBUTING.md) for this project.
- [x ] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-recipes/blob/HEAD/CODE_OF_CONDUCT.md) that this project adheres to.
Since a few months certain links on instagram.com have started to open in the external browser, regardless of the service preference to open links in Ferdium. This issue is fixed with an adaptation of the event filter in the custom website recipe, modified to ignore NULL and script links (`#`).
Also fixes an occasional `element == null` dereference in getMessages().
Fixes: https://github.com/ferdium/ferdium-app/issues/1304
=> Ensure that links are opened according to the user's preference

README.md, package.json
Put the validation checks in a more noticeable place.
I've noticed a lot of PRs that fail the checks. A lot of the time, the error message says it's a `pnpm package` error message asking for a version bump, even when the `package.json` already has a version bump. It's usually because the two other commands edited the files when they were run, and if the changes weren't staged ahead of time locally, `pnpm package` sees the new changes and fails the build.
It seems that a lot of people either didn't read the validation checks in the docs, or forgot (as I did with my latest PR). So, I'm thinking it might be a good idea to tell/remind people of the validation checks and put the info in a more prominent place.
=> Make the validation checks more noticeable

recipes/telegram/index.js, recipes/telegram/package.json
Here is a [recorded screencast](https://youtu.be/Jc-QQZw5QVE) how I sent a message to myself and a notification appears in the top-right corner.
I've identified the reason why Telegram Web A's notifications don't make it through in Ferdium:
Telegram A [sends notifications to the service worker](https://github.com/Ajaxy/telegram-tt/blob/8fc3df855df4a1d9914e90e9e4ac8c85c2d3dd61/src/util/notifications.ts#L484-L500) to handle them if push notifications are supported:
```js
if (checkIfPushSupported()) {
if (navigator.serviceWorker?.controller) {
// notify service worker about new message notification
navigator.serviceWorker.controller.postMessage({
type: 'showMessageNotification',
payload: {
title,
body,
icon,
chatId: chat.id,
messageId: …
```
=> Fix message notifications in Telegram

recipes/discord/package.json, recipes/discord/webview.js
Added code to Discord's webview.js so that file downloads will always be opened by Ferdium instead of an external browser, even if the user wants most web links to open outside of Ferdium.
=> Handle Discord download links within Ferdium

recipes/messenger/darkmode.css, recipes/messenger/package.json
- [] I have read the [Contributing Guidelines](https://github.com/ferdium/ferdium-recipes/blob/HEAD/CONTRIBUTING.md) for this project.
- (That file doesn't exist in this repo.)
Messenger made a change to add a new color definition for incoming message bubbles, and as a result, they are now white with gray text, and thus difficult and painful to read. This CSS change adds that color definition with the previously used message color to correct that.
Thanks kindly! 😊
=> Messenger: Add color definition for incoming message bubbles.

recipes/whatsapp/package.json, recipes/whatsapp/webview.js
preventing the Whatsapp unread count from pulling the count of archived chats.
details:
as mentioned in this issue [#1118](https://github.com/ferdium/ferdium-app/issues/1118) which was fixed before but then the problem comeback after this commit [Fix WhatsApp count](https://github.com/ferdium/ferdium-recipes/commit/fd169b7b2ad80abce5b044909d5234f0ea6a1c27) as it solved the count but returned back to counting archived chats
I have opened the issue again before I fix it: [#451](https://github.com/ferdium/ferdium-recipes/issues/451)
=> prevent pulling archived chats unread count

recipes/messenger/package.json, recipes/messenger/webview.js
=> Update Messenger link handling

recipes/discord/package.json, recipes/discord/webview.js
Discord numbered unread message badges as well as all new message badge is currently not working. This will fix both of these issues. As discussed here https://github.com/ferdium/ferdium-app/issues/1370
=> Fix Discord badge counts

recipes/zoho/package.json, recipes/zoho/webview-unsafe.js
As `window.zmNCenter` which was used to get notifications count for the badge's indirect notifications part does not exist anymore, badge for Zoho Mail was not working.
The solution was to retrieve notifications count differently and to exclude Zoho Mail specific `window` properties from the `if` condition so the badge would be affected only partially if one of the used Zoho Mail `window` properties gets removed in the future. For example, if `zmTopBar` will be removed from `window`, retrieval of the direct messages count would
still work.
Additionally unread chats count was added to Zoho Mail badge's direct notifications.
=> Fix Zoho Mail badge

recipes/instagram-direct-messages/package.json, recipes/instagram-direct-messages/webview.js, recipes/instagram/package.json, recipes/instagram/webview.js
I have fixed the badge of notifications for the Instagram and Instagram-direct-messages applications. The query selector now directly retrieves the value within the <span> that contains the number of notifications.
=> fix badge for Instagram

recipes/nextcloud-calendar/package.json, recipes/nextcloud-calendar/service.css, recipes/nextcloud-calendar/webview.js
Script and CSS was updated to add selectors for the latest Nextcloud (27).
Previous selectors were left as is for backwards compatibility.
=> Fix selectors in the Nextcloud Calendar recipe

recipes/nextcloud-talk/package.json, recipes/nextcloud-talk/service.css, recipes/nextcloud-talk/webview.js
Script and CSS was updated to add selectors for the latest Nextcloud (27).
Previous selectors were left as is for backwards compatibility.
Additionally direct notifications count now is detected by unread conversations count in the left sidebar, using Talk specific notifications as a fallback.
Fixes ferdium/ferdium-app#971
This pull request replaces #470 which got automatically closed by accidentally deleting the source branch.
=> Fix selectors for Nextcloud Talk

package.json, recipes/gmail/package.json, recipes/gmail/webview.js
Thanks to all y'all for this recipe!
I use it with G-Suite and have missed a few important messages from only seeing Ferdium count emails and not chat messages.
Makes the badge account for chat messages from DMs and Spaces.
Also, unlocks version lock. I ran everything just fine with Node 20.10.0 and pnpm 8.12.1
=> Adds Spaces and Chat badges to countImportant

recipes/github/package.json, recipes/github/webview.js
GitHub recipe was updated to append a new selector for indirect notifications badge that works when an user navigates to GitHub Gist.
=> Add a new selector for indirect GitHub notification badge

recipes/github/package.json, recipes/github/webview.js
GitHub recipe's `webview.js` was updated to move `newCountMatch` definition within `getMessages` so unread messages badge would be correctly updated when the "x new notification(s)" link appears.
=> GitHub recipe  - fix unread count retrieval from new notififications link

recipes/rocketchat/package.json, recipes/rocketchat/webview.js
At some point, Rocketchat started to remove the DOM elements for channels from the sidebar which are not in the current viewport (i.e. scrolled out of view). This means that the current approach of counting `.rcx-badge` and `.rcx-sidebar-item--highlighted` elements does not work reliably, since they might not exist.
The recipe now uses the information in the title bar, which is updated by Rocketchat itself.
=> rocketchat: fix unread counter disappearing

.github/PULL_REQUEST_TEMPLATE.md
change url in template request
Add row check list for update package version
=> update template PR

recipes/office365-owa/package.json, recipes/office365-owa/webview.js
Fixes unread count when not having onlyShowFavoritesInUnreadCount set to true.
Note: Groups are still broken, they're no longer a child of the nav bar or something.
=> Office365: Fix selector for "Folders"

recipes/groupme/package.json, recipes/groupme/webview.js
The previous code for this recipe implies that the GroupMe web app used to use Angular(JS), given that it was filtering based on an .ng-hide class. In use, the plugin was simply returning all conversation threads, rather than filtering for unread and unmuted conversations. So if there were 7 total, read conversations, the notification badge showed 7.
This update queries for conversations that have the much more direct .unread class and also do not contain the muted class inside them. This has made the notification badge count accurate for me.
=> Update GroupMe DOM filtering to use latest web app conventions

package.json, scripts/create.mjs
with the upgrade of the [open](https://www.npmjs.com/package/open) package to: open@9.1.0 (six months ago)
the `/scripts/create.js` is invalid because this version is [ESM](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Modules) only.
i ported the entire app to ESM.
=> porting to use ESM

recipes/google-voice/darkmode.css, recipes/google-voice/package.json
Dark mode change required for a recent Google Voice update. Text message input field had an additional style added on the service's end, and this PR compensates for it in dark mode
=> Google Voice Dark Mode update

recipes/whatsapp/package.json, recipes/whatsapp/service.css
Add a new selector class `.app-wrapper-web ._aigs` to disable `max-width`
Add `.app-wrapper-web ._aigs` as a new selector to disable `max-width`.
Resolves ferdium/ferdium-app#1664
=> Whatsapp - Disable max-width on new main app selector

recipes/notion-calendar/package.json, recipes/notion-calendar/webview-unsafe.js, recipes/notion-calendar/webview.js
This is a workaround fix to Notion Calendar login with Google - we need to capture and change the login URL (`popup=true` to `popup=false`) so that the user can login inside the webview.
=> Fix notion calendar login

docs/configuration.md, scripts/package.js
After some discussion with @vraravam we came to the conclusion that SVG increase local bundle size for users, which is unnecessary given users can fetch the static assets generated by `jsdelivr`.
Indeed, before this PR total package bundle of all recipes was 7.34 MB and now it is 377 KB, which is ~19.5 times smaller.
To test this PR do the following:
- Checkout the PR in the main repo: https://github.com/ferdium/ferdium-app/pull/1740
- Go to the `recipes` submodule and add my `ferdium-recipes` fork as a remote
- Checkout this branch PR
- Run `pnpm i` and `pnpm package`
- Go back to the main repo folder
- Compile the app and run it for the first time (add 2 or 3 recipes)
- Go to your system folder (in case of Windows …
=> chore: change icons to reduce bundle

recipes/msteams/package.json, recipes/msteams/webview.js
Fix for badges on Teams V2 (new Teams)
This closes https://github.com/ferdium/ferdium-app/issues/1744
=> Fix for badges on Teams V2 (new Teams)

scripts/package.js
1. Minor refactoring to use consistent `fs.existsSync` for files.
2. Also, fixed a bug where, if the `icon.svg` file was missing, the packaging step would error out.
=> Handle case correctly where the 'icon.svg' file isn't present

scripts/package.js
As explain [in this issue](https://github.com/ferdium/ferdium-app/issues/1778), we cannot validate PR for recipes because `pnpm validate` is still a failure.
Script compare the list of detected change where path are like "recipes/hangoutschat/package.json" and pkgJsonRelative contaning path to package.json with this format "recipes\hangoutschat\package.json".
Of course, it never match.
Change : add path normalization on pkgJsonRelative
=> Normalize path in pkgJsonRelative before comparing

recipes/hangoutschat/package.json, recipes/hangoutschat/webview.js
Change the method for detecting unread messages, because using div classes is broken every time Google chat is updated (this is currently the case)
=> Fix the method for detecting unread messages for Google Chat

recipes/whatsapp/package.json, recipes/whatsapp/service.css
Removes an outdated css definition that breaks the status page on whatsapp.
Can't seem to find the notice the original rule mentions.
Fix https://github.com/ferdium/ferdium-app/issues/1774
=> Fix missing elements and margin on Whatsapp's status page

recipes/icloud-mail/icon.svg, recipes/icloud-mail/index.js, recipes/icloud-mail/package.json, recipes/icloud-mail/webview.js
=> Add iCloud Mail recipe

recipes/discord/index.js, recipes/discord/package.json
For an unknown reason, when Discord sees `Apple macOS` in the user agent, it defaults to the mobile/tablet version of the website instead of the desktop version. Replacing it with the string `Intel Mac OS X` fixes the issue.
=> Fix discord going to mobile version on mac

recipes/github/package.json, recipes/github/webview.js
Because of recent changes in GitHub unread notifications count from the bubble next to "Inbox" was not correctly detected, so the selector was updated to fix this.
=> Fix selector for unread GitHub notifications count

recipes/google-calendar/darkmode.css, recipes/google-calendar/package.json
This updates Google Calendar's dark mode to version 20240912.0.1 extracted from https://github.com/EvHaus/google-redesigned.
This styling was added in https://github.com/ferdium/ferdium-recipes/pull/575 and requires updates from time to time as Google has a tendency of breaking compatibility.
=> Google Calendar Dark Mode updated to v20240912.0.1

.github/workflows/builds.yml, package.json
=> Fix github workflow file: pnpm command has to be run after node installation

scripts/create.mjs
Adding support for Microsoft Windows in the recipe-create-script
PS: I leave the version upgrade to the maintainers
=> Adding support for Micosoft Windows

recipes/deepseek/package.json
I don't use this service myself, but according to https://github.com/ferdium/ferdium-app/issues/2029, the previous url was causing problems with chats not staying inside Ferdium but opening in the general browser.
=> fix(deepseek): change url to chat
