package.json
Related to https://github.com/ferdium/ferdium-app/pull/21#discussion_r855885630.
=> build: add pnpm version to package.json#engines

recipes/github/package.json
=> Support for self-hosted github

recipes/messenger/darkmode.css, recipes/messenger/package.json
Changes copied from https://github.com/ducfilan/Dark-mode-Franz-Ferdi (attribution already present in the file)
I haven't tested this since I dont use FB. Please test and then approve.
=> Updated dark mode for 'messenger' service

recipes/nextcloud-talk/package.json, recipes/nextcloud-talk/webview.js
=> Nextcloud-Talk has missing character in selector

recipes/nextcloud-calendar/index.js, recipes/nextcloud-calendar/package.json, recipes/nextcloud-calendar/service.css, recipes/nextcloud-calendar/webview.js, recipes/nextcloud-carnet/index.js, recipes/nextcloud-carnet/package.json, recipes/nextcloud-carnet/service.css, recipes/nextcloud-carnet/webview.js, recipes/nextcloud-cospend/index.js, recipes/nextcloud-cospend/package.json, recipes/nextcloud-cospend/service.css, recipes/nextcloud-cospend/webview.js, recipes/nextcloud-news/package.json, recipes/nextcloud-news/service.css, recipes/nextcloud-news/webview.js, recipes/nextcloud-talk/index.js, recipes/nextcloud-talk/package.json, recipes/nextcloud-talk/service.css, recipes/nextcloud-talk/webview.js, recipes/nextcloud-tasks/index.js, recipes/nextcloud-tasks/package.json, recipes/nextcloud-tasks/service.css, recipes/nextcloud-tasks/webview.js
This commit fixes the parsing algorithm for the website to use `safeParseInt` across all Nextcloud applications, modifies the default items on the settings dropdown menu to be better localized to each individual page, and corrects the format of the URL to better accommodate the custom servers used by Nextcloud.
=> Add fixes for Nextcloud-related webapps

recipes/messenger/package.json, recipes/messenger/webview.js
| Before <br /> ![image](https://user-images.githubusercontent.com/37463445/176475616-28b537bd-06f6-4e11-80cf-790464a7dbea.png) | After <br /> ![image](https://user-images.githubusercontent.com/37463445/176478087-6ff6bf48-ef05-453f-824c-d1ec2f14e692.png) |
| -- | -- |
This is running on loop because I can't see how to implement it otherwise.
=> Hide 'install messenger' button

package.json
=> Upgrade 'pnpm' to '7.4.1'

recipes/messenger/package.json, recipes/messenger/webview.js
Fix pre-commit hooks on Messenger as requested in https://github.com/ferdium/ferdium-recipes/commit/016e7fe37956b6dec1682d9f4538c48789944613#r77512324
=> Fix pre-commit hooks on Messenger

recipes/discord/index.js, recipes/discord/package.json
=> Explicitly use user agent of chrome for discord receipe. Fixes #31

recipes/zammad/icon.svg, recipes/zammad/index.js, recipes/zammad/package.json, recipes/zammad/webview.js
Zammad is a ticketing system that is self-hosted.
=> Add Zammad recipe

recipes/office365-owa/package.json
Reopening this PR (https://github.com/ferdium/ferdium-recipes/pull/9) in favor of this https://github.com/ferdium/ferdium-recipes/issues/8#issuecomment-1158696194.
This fixes https://github.com/ferdium/ferdium-recipes/issues/8
=> Outlook issue

recipes/bitbucket/package.json
=> Allow self-hosted option for bitbucket

recipes/telegram/package.json, recipes/telegram/webview.js
Partially fixes ferdium/ferdium-app#93 and  ferdium/ferdium-app#434
=> Fix issue with telegram web-k not being recognized correctly

docs/frontend_api.md, recipes/discord/package.json, recipes/discord/webview.js, recipes/zoom/package.json, recipes/zoom/webview.js
1. Please remember that if you are logging a bug for some service that has _stopped working_ or is _working incorrectly_, please log the bug [here](https://github.com/ferdium/ferdium-recipes/issues)
2. If you are requesting support for a **new service** in Ferdium, please log it [here](https://github.com/ferdium/ferdium-recipes/pulls)
3. Please remember to read the [self-help documentation](https://github.com/ferdium/ferdium-app#troubleshooting-recipes-self-help) - in case it helps you unblock yourself for issues related to older versions of recipes that were installed on your machine. (These will get automatically upgraded when you upgrade to the newer versions of Ferdium, but to get new recipes between Ferdium releases, this documentation is quite useful.)
4. Please ensure you've …
=> Change isImage to link and stayInsideDiscord

package.json, recipes/discord/package.json, recipes/discord/webview.js
Same thing as https://github.com/ferdium/ferdium-app/pull/475 but for recipes. Also, fix previous lint error.
=> Fix lint and prettier

docs/integration.md
per https://github.com/getferdi/recipes/blob/master/docs/integration.md and testing, I think it should be `pnpm run create <recipe>`. However, I don't know pnpm particularly well.
=> fix pnpm run create directions

recipes/magic-level/icon.svg, recipes/magic-level/index.js, recipes/magic-level/package.json, recipes/magic-level/service.css, recipes/magic-level/webview.js
=> Add Magic Level recipe

recipes/whatsapp/package.json, recipes/whatsapp/service.css, recipes/whatsapp/webview.js
All Whatsapp popups were being hijacked by this implementation. Reverting for now.
This reverts commit 6b2bc506c212e88359f06107097ac4446bd5216f.
=> Revert "fix: add warning to whatsapp theming (#138)"

recipes/onmail/icon.svg, recipes/onmail/index.js, recipes/onmail/package.json, recipes/onmail/webview.js
OnMail is a new [email service by Edison](https://www.onmail.com/).
Added unread count for all inboxes
=> Add service OnMail

recipes/bugzilla/icon.svg, recipes/bugzilla/index.js, recipes/bugzilla/package.json, recipes/bugzilla/webview.js
Closes: https://github.com/ferdium/ferdium-recipes/issues/150
Signed-off-by: Maciej Barć <xgqt@gentoo.org>
=> recipes: add initial Bugzilla service

recipes/discourse/icon.svg, recipes/discourse/index.js, recipes/discourse/package.json, recipes/discourse/webview.js
Closes: https://github.com/ferdium/ferdium-recipes/issues/149
Signed-off-by: Maciej Barć <xgqt@gentoo.org>
=> recipes: add initial Discourse service

recipes/franz-custom-website/package.json, recipes/franz-custom-website/webview.js
=> Allow custom recipe to trapLinks and open them within Ferdium

recipes/kimaicloud/package.json
=> Kimai recipe now has the option for a custom domain

recipes/telegram/package.json, recipes/telegram/webview.js
=> Telegram links can open within Ferdium instead of default browser

recipes/discord/package.json
The domain for Discord service changed from discordapp.com to discord.com some time ago, changed the domain.
=> updated Discord domain to discord.com

recipes/onmail/package.json, recipes/onmail/webview.js
- Element that contains the unread count dissapears when count is zero.
- Added that scenario to reset th ecount to zero and send it to the badge
=> Fix: Unread count stays at 1 when all emails are read

recipes/pocketcasts/icon.svg, recipes/pocketcasts/index.js, recipes/pocketcasts/package.json, recipes/pocketcasts/webview.js
=> Add new recipe: PocketCasts

recipes/whatsapp/package.json, recipes/whatsapp/webview.js
Fixes https://github.com/ferdium/ferdium-recipes/issues/230.
As discussed in https://github.com/ferdium/ferdium-recipes/pull/235
=> fix: Use IndexedDB for updating whatsapp unread message count

recipes/nextcloud/package.json, recipes/nextcloud/webview.js
These changes should be backwards compatible, but I did not have a chance to test them with earlier Nextcloud versions.
=> Fix notifications count for Nextcloud 25

recipes/reclaim/icon.svg, recipes/reclaim/index.js, recipes/reclaim/package.json, recipes/reclaim/webview.js
=> add new recipe: Reclaim

recipes/chatgpt/package.json, recipes/chatgpt/webview.js
Add darkmode handling to ChatGPT
=> feat: add darkmode to chatgpt recipe

recipes/bitwarden/package.json, recipes/cinny/package.json, recipes/element/package.json
fixes [#936](https://github.com/ferdium/ferdium-app/issues/936)
=> fix #936: Rectify serviceUrls for known problematic services

recipes/hangouts/package.json, recipes/hangouts/webview.js
Fixed the counting of the notifications in the Hangouts recipe.
=> Fix Hangouts badge counter

recipes/googlecalendar/package.json, recipes/googlecalendar/webview.js
- Detect when is in the landing page to redirect to the login page (replicate the same behaviour as gmail recipe)
- Bump version to 2.3.2
=> Fix Google Calendar landing page

recipes/oreilly-learning/icon.svg, recipes/oreilly-learning/index.js, recipes/oreilly-learning/package.json, recipes/oreilly-learning/webview.js
Add new recipe for O'Reilly learning.
Logo has been adapted from https://seeklogo.com/vector-logo/442336/oreilly.
=> Add O'Reilly Learning recipe

recipes/chatwithgpt/icon.svg, recipes/chatwithgpt/index.js, recipes/chatwithgpt/package.json, recipes/chatwithgpt/webview.js
I added a Chat with GPT recipe, closes https://github.com/ferdium/ferdium-app/issues/1114
=> Add Chat with GPT recipe

recipes/posteo/package.json
Fixes https://github.com/ferdium/ferdium-app/issues/953
=> Fix posteo recipe logging out at reload

recipes/instagram-direct-messages/package.json, recipes/instagram-direct-messages/webview.js
Currently, Instagram Direct Messages’ unread count never increments. I updated the count method to a more robust one.
=> Fix Instagram Direct Messages count

recipes/yandex-mail/package.json, recipes/yandex-mail/webview.js
Update unread count using a small `unread` button under the inbox categories list.
=> Update unread count for yandex-mail

recipes/bluesky/icon.svg, recipes/bluesky/index.js, recipes/bluesky/package.json, recipes/bluesky/webview.js
Added a Bluesky recipe, closes https://github.com/ferdium/ferdium-app/issues/1138.
I didn’t implement an unread messages count though, as Bluesky has a waitlist and I don’t have an account, so I can’t do any further testing.
=> Add Bluesky recipe

package.json, pnpm-lock.yaml
Upgrade the following node modules:
```
all-contributors-cli 6.24.0 -> 6.25.0
eslint 8.34.0 -> 8.39.0
fs-extra 11.1.0 -> 11.1.1
prettier 2.8.4 -> 2.8.8
simple-git 3.16.0 -> simple-git 3.18.0
```
=> Upgrade node modules

docs/integration.md
Correct link as reported by https://github.com/ferdium/ferdium-app/pull/948#issuecomment-1538784513
=> docs: update link to report issues

recipes/nextcloud-deck/README.md, recipes/nextcloud-deck/icon.svg, recipes/nextcloud-deck/index.js, recipes/nextcloud-deck/package.json, recipes/nextcloud-deck/service.css, recipes/nextcloud-deck/webview.js
- [✔️] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-recipes/blob/HEAD/CODE_OF_CONDUCT.md) that this project adheres to.
Added Nextcloud Deck Recipe using other Nextcloud Recipes as a base. Icon was edited by myself. See recipes/nextcloud-deck/README.md for further details.
=> Add Nextcloud Deck Recipe

recipes/proton-mail/icon.svg, recipes/proton-mail/package.json, recipes/protoncalendar/icon.svg, recipes/protoncalendar/package.json, recipes/protondrive/icon.svg, recipes/protondrive/package.json
Update to the outdated Proton Calendar logo. Protonmail and Proton Drive logos were mobile ones, so changed to website and desktop logos for better uniformity within Ferdium.
=> Update to logos for Proton services

package.json
Upgrade `pnpm` to the latest version `8.5.1`
=> Upgrade 'pnpm' to '8.5.1'

package.json, pnpm-lock.yaml
=> Upgrade 'pnpm' to '8.6.2'

recipes/telegram/package.json, recipes/telegram/webview.js
Fixes Telegram WebZ/A not showing unread counters.
=> Update counter for Telegram webZ

package.json, recipes/bard/package.json, recipes/bluesky/package.json, recipes/chatwoot/package.json, recipes/feedly/package.json, recipes/freshdesk/package.json, recipes/instagram-direct-messages/package.json, recipes/miro/package.json, recipes/mirotalk-c2c/package.json, recipes/mirotalk-p2p/package.json, recipes/mirotalk-sfu/package.json, recipes/mirotalk-webrtc/package.json, recipes/office365-owa/package.json, recipes/office365-owa/webview.js, recipes/perplexity/package.json, recipes/reclaim/package.json, recipes/skiff-mail/package.json, recipes/skype/package.json, recipes/tchap/package.json, recipes/teamweek/package.json, recipes/telegram/package.json, recipes/telegram/webview.js, recipes/tixio/package.json, recipes/whatsapp/package.json, scripts/create.js, scripts/package.js
Mimics https://github.com/ferdium/ferdium-app/pull/1281 to enhance lint setup
@mcmxcdev - please review
=> Improve lint setup

recipes/reddit/package.json, recipes/reddit/webview.js
This fixes https://github.com/ferdium/ferdium-app/issues/1325 by deleting old code (I think the code was trying to skip some ads, but now it seems that removes all elements entirely).
=> Fix Reddit webpage not rendering

recipes/franz-custom-website/package.json, recipes/franz-custom-website/style.css
Fixes https://github.com/ferdium/ferdium-app/issues/1326 by removing the style.css file entirely (as it no longer fits its purpose)
=> Remove background color css of custom websites

package.json, pnpm-lock.yaml
Upgrade pnpm and node modules.
=> Upgrade 'pnpm' to '8.7.1'; Upgrade npm modules (minor version bumps).

recipes/pushover/package.json, recipes/pushover/webview.js
change to count message using message_row class quantity instead app_counter(not exist)
=> Update PushOver notification count

recipes/instagram/package.json, recipes/instagram/webview.js
Instagram started to use relative paths (maybe to optimize their website). We should not catch those.
This fixes https://github.com/ferdium/ferdium-app/issues/1403
=> Instagram fix (#1403)

recipes/tiktok/package.json, recipes/tiktok/webview.js
I just changed the selectors cause I noticed the notifications were not showing.
=> Update notification selectors for TikTok

recipes/github/package.json, recipes/github/webview.js
Selector for finding out whether an indirect notification is present was updated.
=> Fix indirect notifications badge for GitHub

recipes/zulip/package.json, recipes/zulip/webview.js
Zulip changed classes/unread styles a while ago - this fixes it.
=> Zulip changed unread locations

package.json
- update `volta` config in `package.json` to use exact versions
=> fix: invalid volta versions in package.json

recipes/google-voice/darkmode.css, recipes/google-voice/package.json
For Google Voice darkmode.css - fixes dark mode colors for message links and dark modes some additional side panels that were missed in #449
=> Google Voice darkmode.css, fix message links and additional side panels

recipes/google-voice/darkmode.css, recipes/google-voice/package.json
Add dark background for search results
=> Google Voice Dark background for search results

recipes/messenger/darkmode.css, recipes/messenger/package.json
Fixed the white background issue in FB messenger dark mode.
=> Fix white background in messenger recipe dark mode

recipes/gmail/package.json, recipes/gmail/webview.js
Fixes https://github.com/ferdium/ferdium-app/issues/1496
=> Fix unread counts in gmail

recipes/anonaddy/package.json
Service has migrated to a new name and url recently.
=> Change name and serviceUrl of anonaddy

recipes/discord/package.json
This should make the app load more quickly and prevent unintended logouts.
Fixes ferdium/ferdium-app#1124.
=> Set more appropriate Discord `serviceURL`

recipes/anonaddy/package.json
This fixes https://github.com/ferdium/ferdium-app/issues/1541
=> fix: addy.io self host option

package.json, pnpm-lock.yaml, recipes/zalo/package.json, recipes/zalo/webview.js
1. Upgrade `pnpm` to latest `8.15.1`
2. Upgrade all other deps (tiny and minor versions) where they are drop-in upgrades without other changes.
=> upgrade pnpm and other deps

.github/workflows/builds.yml, .github/workflows/check-pr.yml
General housekeeping to upgrade GHA actions - triggered as warnings in the GHA screen for previous builds.
=> upgrade GHA actions to newer versions

.github/dependabot.yml
=> Update dependabot.yml to handle both app and GHA dependencies

.gitignore
Ignore files generated by the `zrecompile` utility
=> ignore zsh-compiled files [skip ci]

recipes/slack/package.json, recipes/slack/webview.js
Prevent 'free trial ending soon' sidebar item to be counted as unread message
=> Ignore 'free trial ending soon' sidebar item

recipes/google-voice/darkmode.css, recipes/google-voice/package.json
Adds dark styling to add contacts in Google Voice
=> Google Voice darkmode update for add contact

package.json
=> Upgrade pnpm to 8.15.5

recipes/bluesky/package.json
Change bluesky uril from staging to prod. Fixes [#1637](https://github.com/ferdium/ferdium-app/issues/1637)
=> Change bluesky url from staging to prod

recipes/proton-pass/icon.svg, recipes/proton-pass/index.js, recipes/proton-pass/package.json, recipes/proton-pass/webview.js
This adds a recipe for the service Proton Pass. It's a standard recipe; the only difference is that I set the user agent to Firefox to avoid a top bar that suggests installing the extension for Proton Pass for Chrome, since it isn't relevant.
=> Add recipe for Proton Pass

recipes/proton-mail/package.json, recipes/proton-mail/webview.js
- narrow down selector to grab counter from "inbox" entry
Closes https://github.com/ferdium/ferdium-app/issues/1651
=> fix: proton mail scheduled emails are shown in unread message badge

package.json, pnpm-lock.yaml, scripts/package.js
=> Upgrade pnpm to 9.0.6

recipes/azure-portal/icon.svg, recipes/azure-portal/index.js, recipes/azure-portal/package.json, recipes/azure-portal/webview.js
Azure devops recipe exists, but one for portal does not, in this PR it will be added.
=> feat(recipes): add azure portal recipe

recipes/whatsapp/package.json, recipes/whatsapp/service.css
This PR hides the message to install the Whatsapp desktop app.
=> fix: whatsapp install desktop notice

package.json, pnpm-lock.yaml
Upgrade pnpm to 9.1.4
According to @Alphrag :
A few things that I have seen that are good in it: it uses node-gyp v10.x which means rebuilding some dependencies won't fail (like sqlite3 if we wish at one point to upgrade it again to the latest version, but is not recommended atm), and allows shorter paths of included node-modules for windows which could fix a problem for some users
=> Upgrade pnpm to 9.1.4

package.json, pnpm-lock.yaml
=> Deps upgrade

recipes/invoice-ninja/package.json
Invoice Ninja service was already present with hosted service URL.  
This commit activates the self-hosted option with custom URL.
=> Add self-hosted option for Invoice Ninja

recipes/google-calendar/darkmode.css, recipes/google-calendar/package.json
This updates google-calendar's darkmode's css to use the styling from https://github.com/EvHaus/google-redesigned, a more maintained and good-looking version.
> See https://github.com/ferdium/ferdium-app/issues/1846 for how it looks right now
You can demo this change by inserting https://raw.githack.com/eitchtee/google-redesigned-ferdium/master/css/calendar.user.css on your own google-calendar `webview.js` as I've been keeping a version of this styling for my own use on Ferdium for quite some time now.
fixes https://github.com/ferdium/ferdium-app/issues/1846
=> Improve google-calendar's darkmode styling

recipes/yahoo-mail/package.json, recipes/yahoo-mail/webview.js
Badge number was not changing when all mails were read.
=> fix(yahoo-mail): update badge to 0 when all mail is read

.github/workflows/builds.yml, .github/workflows/check-pr.yml
Upgraded GHA runner OSes based on the deprecation notice from [this page](https://github.com/actions/runner-images?tab=readme-ov-file#available-images).
=> Upgrade all GHA runner OSes to latest stable versions

.github/workflows/check-recipe-version-bump/action.yml
Updated gh action to node20 to suppress warnings
=> Updated actions to node20

recipes/it-tools/index.js, recipes/it-tools/package.json, recipes/it-tools/webview.js
=> Add IT-Tools

recipes/paperless-ngx/index.js, recipes/paperless-ngx/package.json, recipes/paperless-ngx/webview.js
=> Add Paperless-NGX Recipe

recipes/techmeme/icon.svg, recipes/techmeme/index.js, recipes/techmeme/package.json, recipes/techmeme/webview.js
Adds the techmeme news page as a new recipe
=> Add techmeme recipe
